# Generated by Django 3.1.1 on 2020-10-05 06:34

from django.db import migrations, models
import django.db.models.deletion
import djrichtextfield.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LeagueSelection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('league_selection', models.CharField(blank=True, max_length=60, null=True)),
                ('status', models.CharField(choices=[('1', 'ACTIVE'), ('0', 'INACIVE')], default='1', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MatchFormat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_format', models.CharField(blank=True, max_length=60, null=True)),
                ('status', models.CharField(choices=[('1', 'ACTIVE'), ('0', 'INACIVE')], default='1', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MatchManage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_teams', models.CharField(choices=[('1', '1 TEAM'), ('2', '2 TEAMS'), ('3', '3 TEAMS'), ('4', '4 TEAMS'), ('5', '5 TEAMS'), ('6', '6 TEAMS'), ('7', '7 TEAMS'), ('8', '8 TEAMS'), ('9', '9 TEAMS'), ('10', '10 TEAMS'), ('11', '11 TEAMS')], max_length=60)),
                ('match_start_date', models.DateField(blank=True, null=True)),
                ('match_time', models.TimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('1', 'ACTIVE'), ('0', 'INACIVE')], default='1', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('league_selection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leagueselection', to='dashboard.leagueselection')),
                ('match_format', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matchformat', to='dashboard.matchformat')),
            ],
            options={
                'verbose_name_plural': 'Match Manage',
            },
        ),
        migrations.CreateModel(
            name='MatchType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_type', models.CharField(blank=True, max_length=60, null=True)),
                ('status', models.CharField(choices=[('1', 'ACTIVE'), ('0', 'INACIVE')], default='1', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderManage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=60, null=True)),
                ('standard', models.CharField(blank=True, max_length=60, null=True)),
                ('status', models.CharField(choices=[('1', 'ACTIVE'), ('0', 'INACIVE')], default='1', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PackageManage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_name', models.CharField(blank=True, max_length=60, null=True)),
                ('package_price', models.CharField(blank=True, max_length=60, null=True)),
                ('discount_price', models.CharField(blank=True, max_length=60, null=True)),
                ('description', djrichtextfield.models.RichTextField(blank=True, null=True)),
                ('select_month', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11)])),
                ('select_day', models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20), (21, 21), (22, 22), (23, 23), (24, 24), (25, 25), (26, 26), (27, 27), (28, 28), (29, 29), (30, 30)], null=True)),
                ('package_imageUpload', models.ImageField(blank=True, null=True, upload_to='', verbose_name='upload/images/')),
                ('package_status', models.CharField(choices=[('1', 'Trending'), ('2', 'Big Winning'), ('0', 'None')], default='0', max_length=1)),
                ('status', models.CharField(choices=[('1', 'ACTIVE'), ('0', 'INACIVE')], default='1', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Package',
            },
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series_name', models.CharField(blank=True, max_length=60, null=True)),
                ('series_start_date', models.DateField(blank=True, null=True)),
                ('series_end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('1', 'ACTIVE'), ('0', 'INACIVE')], default='1', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Series',
            },
        ),
        migrations.CreateModel(
            name='TeamManage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(blank=True, max_length=60, null=True)),
                ('short_name', models.CharField(blank=True, max_length=60, null=True)),
                ('team_manage_imageUpload', models.ImageField(blank=True, null=True, upload_to='', verbose_name='upload/images/')),
                ('status', models.CharField(choices=[('1', 'ACTIVE'), ('0', 'INACIVE')], default='1', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Team Manage',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(blank=True, max_length=100, null=True)),
                ('user_email', models.EmailField(blank=True, max_length=100, null=True, unique=True)),
                ('user_phone', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('isVerified', models.BooleanField(default=False)),
                ('counter', models.IntegerField(default=0)),
                ('user_social_id', models.CharField(blank=True, max_length=100, null=True)),
                ('user_status', models.CharField(choices=[('0', 'Suspended'), ('1', 'Live')], default='1', max_length=1)),
                ('user_image', models.CharField(blank=True, max_length=300, null=True)),
                ('user_imageUpload', models.ImageField(blank=True, null=True, upload_to='', verbose_name='upload/images/')),
                ('login_type', models.CharField(blank=True, max_length=80, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TeamPlayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(blank=True, max_length=60, null=True)),
                ('player_imageUpload', models.ImageField(blank=True, null=True, upload_to='', verbose_name='upload/images/')),
                ('status', models.CharField(choices=[('1', 'ACTIVE'), ('0', 'INACIVE')], default='1', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('player_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playerteam', to='dashboard.teammanage')),
            ],
            options={
                'verbose_name_plural': 'Players',
            },
        ),
        migrations.CreateModel(
            name='PostManage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', djrichtextfield.models.RichTextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('1', 'ACTIVE'), ('0', 'INACIVE')], default='1', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('add_match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addmatchs', to='dashboard.matchmanage')),
                ('select_package', models.ManyToManyField(blank=True, to='dashboard.PackageManage')),
                ('series_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seriesnames', to='dashboard.series')),
            ],
            options={
                'verbose_name_plural': 'Post Manage',
            },
        ),
        migrations.AddField(
            model_name='matchmanage',
            name='match_team_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teammanage', to='dashboard.teammanage'),
        ),
        migrations.AddField(
            model_name='matchmanage',
            name='match_team_2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teammanages', to='dashboard.teammanage'),
        ),
        migrations.AddField(
            model_name='matchmanage',
            name='match_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matchtype', to='dashboard.matchtype'),
        ),
        migrations.AddField(
            model_name='matchmanage',
            name='series_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seriesname', to='dashboard.series'),
        ),
        migrations.CreateModel(
            name='AddPackageMatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('1', 'ACTIVE'), ('0', 'INACIVE')], default='1', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('add_match', models.ManyToManyField(blank=True, to='dashboard.MatchManage')),
                ('package_manage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packagmanage', to='dashboard.packagemanage')),
            ],
            options={
                'verbose_name_plural': 'Add Match',
            },
        ),
    ]
