# Generated by Django 3.1.1 on 2020-10-05 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20201005_0654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionmanage',
            name='package_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packagename', to='dashboard.packagemanage'),
        ),
        migrations.AlterField(
            model_name='transactionmanage',
            name='user_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='username', to='dashboard.user'),
        ),
    ]
