# Generated by Django 3.1.1 on 2020-10-05 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20201005_0655'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionmanage',
            name='active_data',
            field=models.DateField(blank=True, null=True),
        ),
    ]
