# Generated by Django 3.1.1 on 2020-10-05 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_transactionmanage_active_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transactionmanage',
            old_name='package_name',
            new_name='package_id',
        ),
        migrations.RenameField(
            model_name='transactionmanage',
            old_name='user_name',
            new_name='user_id',
        ),
    ]
