# Generated by Django 3.1.1 on 2020-10-05 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_auto_20201005_1046'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postmanage',
            old_name='add_match',
            new_name='select_match',
        ),
    ]
