# Generated by Django 3.1.1 on 2020-10-08 05:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_teamcreatepost'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transactionmanage',
            options={'verbose_name_plural': 'Order Manage'},
        ),
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=40)),
                ('pupil', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='session', to='dashboard.user')),
            ],
        ),
    ]
