# Generated by Django 3.1.1 on 2020-10-08 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_auto_20201008_0554'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionmanage',
            name='paid_status',
            field=models.CharField(choices=[('1', 'ACTIVE'), ('0', 'INACIVE')], default='0', max_length=1),
        ),
    ]
