# Generated by Django 3.1.1 on 2020-10-08 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_transactionmanage_paid_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packagemanage',
            name='discount_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
