# Generated by Django 3.1.1 on 2020-10-09 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_auto_20201008_1030'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Visitor',
        ),
    ]
