# Generated by Django 3.1.1 on 2020-10-09 06:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_appversion'),
    ]

    operations = [
        migrations.AddField(
            model_name='appversion',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appversion',
            name='status',
            field=models.CharField(choices=[('1', 'ACTIVE'), ('0', 'INACIVE')], default='1', max_length=1),
        ),
        migrations.AddField(
            model_name='appversion',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
