# Generated by Django 3.1.1 on 2020-10-09 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_auto_20201009_0611'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fcm_id',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
