# Generated by Django 3.1.1 on 2020-10-09 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_postmanage_player_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postmanage',
            name='player_name',
        ),
        migrations.AddField(
            model_name='postmanage',
            name='update_post',
            field=models.CharField(default='Fri Oct  9 10:51:17 2020', max_length=60),
        ),
    ]
