# Generated by Django 3.1.1 on 2020-10-09 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_auto_20201009_1051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postmanage',
            name='update_post',
        ),
        migrations.AddField(
            model_name='postmanage',
            name='active_post',
            field=models.CharField(default='Fri Oct  9 10:53:59 2020', max_length=60),
        ),
    ]
