# Generated by Django 3.1.1 on 2020-10-12 06:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0019_auto_20201009_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionmanage',
            name='order_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='postmanage',
            name='active_post',
            field=models.CharField(default='Mon Oct 12 06:57:05 2020', max_length=60),
        ),
    ]
