# Generated by Django 3.1.1 on 2020-10-12 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0020_auto_20201012_0657'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transactionmanage',
            old_name='order_id',
            new_name='orders_id',
        ),
        migrations.AlterField(
            model_name='postmanage',
            name='active_post',
            field=models.CharField(default='Mon Oct 12 06:58:15 2020', max_length=60),
        ),
    ]
