# Generated by Django 3.1.1 on 2020-10-12 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0023_auto_20201012_0659'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionmanage',
            name='order_id',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='postmanage',
            name='active_post',
            field=models.CharField(default='Mon Oct 12 07:11:02 2020', max_length=60),
        ),
    ]
