# Generated by Django 3.1.1 on 2020-10-12 07:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0030_auto_20201012_0723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmanage',
            name='active_post',
            field=models.CharField(default='Mon Oct 12 07:28:00 2020', max_length=60),
        ),
        migrations.AlterField(
            model_name='transactionmanage',
            name='user_orders_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
