# Generated by Django 3.1.1 on 2020-10-12 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0031_auto_20201012_0728'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transactionmanage',
            old_name='user_orders_id',
            new_name='orders_id',
        ),
        migrations.AlterField(
            model_name='postmanage',
            name='active_post',
            field=models.CharField(default='Mon Oct 12 07:33:43 2020', max_length=60),
        ),
    ]
