# Generated by Django 3.1.1 on 2020-10-12 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0033_auto_20201012_0734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmanage',
            name='active_post',
            field=models.CharField(default='Mon Oct 12 07:36:23 2020', max_length=60),
        ),
        migrations.AlterField(
            model_name='transactionmanage',
            name='transactionID',
            field=models.CharField(blank=True, editable=False, max_length=100, null=True),
        ),
    ]
