# Generated by Django 3.1.1 on 2020-10-12 07:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0036_auto_20201012_0738'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactionmanage',
            name='order_id',
        ),
        migrations.AlterField(
            model_name='postmanage',
            name='active_post',
            field=models.CharField(default='Mon Oct 12 07:40:32 2020', editable=False, max_length=60),
        ),
        migrations.AlterField(
            model_name='transactionmanage',
            name='transactionID',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, unique=True),
        ),
    ]
