# Generated by Django 3.1.1 on 2020-10-12 07:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0037_auto_20201012_0740'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionmanage',
            name='order_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='postmanage',
            name='active_post',
            field=models.CharField(default='Mon Oct 12 07:41:12 2020', editable=False, max_length=60),
        ),
        migrations.AlterField(
            model_name='transactionmanage',
            name='transactionID',
            field=models.CharField(blank=True, editable=False, max_length=100, null=True),
        ),
    ]
