# Generated by Django 3.1.1 on 2020-10-12 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0039_auto_20201012_0742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmanage',
            name='active_post',
            field=models.CharField(default='Mon Oct 12 10:11:43 2020', editable=False, max_length=60),
        ),
    ]
