# Generated by Django 3.1.1 on 2020-10-14 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0040_auto_20201012_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmanage',
            name='active_post',
            field=models.CharField(default='Wed Oct 14 11:49:52 2020', editable=False, max_length=60),
        ),
    ]
