# Generated by Django 3.1.1 on 2020-10-15 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0043_auto_20201015_1105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matchmanage',
            name='match_time',
        ),
        migrations.AlterField(
            model_name='postmanage',
            name='active_post',
            field=models.CharField(default='Thu Oct 15 11:08:09 2020', editable=False, max_length=60),
        ),
    ]
