# Generated by Django 3.1.1 on 2020-10-15 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0044_auto_20201015_1108'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchmanage',
            name='match_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='matchmanage',
            name='match_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='postmanage',
            name='active_post',
            field=models.CharField(default='Thu Oct 15 17:15:54 2020', editable=False, max_length=60),
        ),
    ]
