# Generated by Django 3.1.1 on 2020-10-15 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0046_auto_20201015_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchmanage',
            name='match_start_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='postmanage',
            name='active_post',
            field=models.CharField(default='Thu Oct 15 22:32:26 2020', editable=False, max_length=60),
        ),
    ]
