# Generated by Django 3.1.1 on 2020-10-15 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0048_auto_20201015_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchmanage',
            name='match_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='postmanage',
            name='active_post',
            field=models.CharField(default='Thu Oct 15 22:40:15 2020', editable=False, max_length=60),
        ),
    ]
