# Generated by Django 3.1.1 on 2020-10-17 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0053_auto_20201015_2252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmanage',
            name='active_post',
            field=models.CharField(default='Sat Oct 17 23:18:18 2020', max_length=60),
        ),
        migrations.AlterField(
            model_name='teamcreatepost',
            name='team_imageUpload',
            field=models.ImageField(default='pexels-ave-calvar-martinez-4852353_ZZZxG7O.jpg', upload_to='', verbose_name='upload/images/'),
        ),
    ]
