# Generated by Django 3.1.1 on 2020-10-17 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0055_auto_20201017_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmanage',
            name='active_post',
            field=models.CharField(default='Sat Oct 17 23:20:15 2020', max_length=60),
        ),
    ]
