# Generated by Django 3.1.1 on 2020-10-17 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0056_auto_20201017_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmanage',
            name='active_post',
            field=models.CharField(blank=True, default='Sat Oct 17 23:20:54 2020', max_length=60, null=True),
        ),
    ]
