# Generated by Django 3.1.1 on 2020-10-17 17:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0057_auto_20201017_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmanage',
            name='active_post',
            field=models.CharField(default=datetime.datetime(2020, 10, 17, 23, 22, 13, 489508), max_length=60),
        ),
    ]
