# Generated by Django 3.1.1 on 2020-10-17 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0059_auto_20201017_2338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmanage',
            name='active_post',
            field=models.CharField(default='October 17, 2020', max_length=60),
        ),
    ]
