# Generated by Django 3.1.1 on 2020-10-17 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0061_auto_20201017_2343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmanage',
            name='active_post',
            field=models.CharField(default='17 Oct 2020', max_length=60),
        ),
    ]
