# Generated by Django 3.1.1 on 2020-10-17 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0062_auto_20201017_2343'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmanage',
            name='active_post_time',
            field=models.CharField(default='23:47:27', max_length=60),
        ),
    ]
