# Generated by Django 3.1.1 on 2020-10-17 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0065_auto_20201017_2354'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postmanage',
            name='active_post_time',
        ),
        migrations.AlterField(
            model_name='postmanage',
            name='active_post',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
