# Generated by Django 3.1.1 on 2020-10-17 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0068_auto_20201017_2359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmanage',
            name='active_post',
            field=models.CharField(default='17 Oct 2020 00:00:00', max_length=60),
        ),
    ]
