# Generated by Django 3.1.1 on 2020-10-17 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0072_auto_20201018_0003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmanage',
            name='active_post',
            field=models.CharField(default='18 Oct 2020 00:04:10', max_length=60),
        ),
    ]
