# Generated by Django 3.1.1 on 2020-10-17 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0073_auto_20201018_0004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmanage',
            name='active_post',
            field=models.CharField(default='18 Oct 2020 00:17:25', max_length=60),
        ),
        migrations.AlterField(
            model_name='postmanage',
            name='select_package',
            field=models.ManyToManyField(to='dashboard.PackageManage'),
        ),
    ]
