# Generated by Django 3.1.1 on 2020-10-18 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0074_auto_20201018_0017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packagemanage',
            name='discount_price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='postmanage',
            name='active_post',
            field=models.CharField(default='18 Oct 2020 09:28:19', max_length=60),
        ),
    ]
