# Generated by Django 3.1.1 on 2020-10-18 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0077_auto_20201018_2305'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmanage',
            name='active_post_time',
            field=models.CharField(default='23:08:33', max_length=60),
        ),
    ]
