# Generated by Django 3.1.1 on 2020-10-18 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0078_postmanage_active_post_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postmanage',
            name='active_post',
        ),
        migrations.RemoveField(
            model_name='postmanage',
            name='active_post_time',
        ),
    ]
