# Generated by Django 3.1.1 on 2020-10-27 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0079_auto_20201019_0006'),
    ]

    operations = [
        migrations.CreateModel(
            name='demoUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=100, null=True)),
                ('password', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('1', 'ACTIVE'), ('0', 'INACIVE')], default='1', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('select_match_demo', models.ManyToManyField(to='dashboard.PackageManage')),
            ],
        ),
    ]
