# Generated by Django 3.1.1 on 2020-10-27 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0081_auto_20201027_1252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demouser',
            name='password',
        ),
        migrations.RemoveField(
            model_name='demouser',
            name='username',
        ),
        migrations.AddField(
            model_name='demouser',
            name='demoUser',
            field=models.ForeignKey(default=10, on_delete=django.db.models.deletion.CASCADE, related_name='demousername', to='dashboard.user'),
            preserve_default=False,
        ),
    ]
